config {
    type: "table",
    schema: "ecommerce_dataset",
    name: "client_ads_summary"
}

SELECT
    c.client_id,
    SUM(o.price),
    SSM(a.cost)
FROM `quick-filament-472410-q6.ecommerce_dataset.clients` AS c
JOIN `quick-filament-472410-q6.ecommerce_dataset.orders` AS o ON c.client_id = o.client_id
JOIN `quick-filament-472410-q6.ecommerce_dataset.ads_data` AS a ON c.client_id = a.client_id
GROUP BY c.client_id