-- Supponiamo di voler creare una tabella con gli ordini mensili per categoria di prodotto:
config {type: "table" }
SELECT
    p.category,
    EXTRACT(YEAR FROM o.order_date) AS year,
    EXTRACT(MONTH FROM o.order_date) AS month,
    SUM(o.price) AS monthly_revenue
FROM $ref{("ecommerce_dataset.orders")} o
JOIN $ref{("ecommerce_dataset.products")} p ON o.product = p.name
GROUP BY 1,2,3
